#!/bin/sh
echo "Running dotfiles install"

if [ ! -d "$HOME/.oh-my-zsh" ]; then
  git clone git://github.com/robbyrussell/oh-my-zsh.git "$HOME/.oh-my-zsh"
  cd "$HOME/.oh-my-zsh"
  grep -v '!custom' "$HOME/.oh-my-zsh/.gitignore" > "$HOME/.oh-my-zsh/.gitignore.tmp"
  echo "custom" >> "$HOME/.oh-my-zsh/.gitignore.tmp"
  rm -f "$HOME/.oh-my-zsh/.gitignore"
  mv "$HOME/.oh-my-zsh/.gitignore.tmp" "$HOME/.oh-my-zsh/.gitignore"
  git add .gitignore
  git rm custom/example.zsh
  git rm custom/example/example.plugin.zsh
  git commit -m 'Ignore custom directory'
  cd -
  echo "Installed oh-my-zsh"
fi

ln -sfn "$PWD/zsh/zshrc" "$HOME/.zshrc"
rm -rf "$HOME/.oh-my-zsh/custom"
ln -sfn "$PWD/zsh" "$HOME/.oh-my-zsh/"
mv "$HOME/.oh-my-zsh/zsh" "$HOME/.oh-my-zsh/custom"
echo "Linked zshrc, oh-my-zsh custom directory"

ln -sfn "$PWD/zsh/bashrc.sh" "$HOME/.bashrc"
echo "Linked bashrc"

ln -sFn "$HOME/Dropbox/dotfiles/chef" "$HOME/.chef"
echo "Linked chef"

ln -sfn "$PWD/ruby/nterchange" "$HOME/.nterchange"
ln -sfn "$PWD/ruby/rvmrc" "$HOME/.rvmrc"
ln -sfn "$PWD/ruby/powconfig" "$HOME/.powconfig"
ln -sfn "$PWD/ruby/gemrc" "$HOME/.gemrc"
ln -sfn "$PWD/ruby/autotest" "$HOME/.autotest"
ln -sfn "$PWD/ruby/irbrc" "$HOME/.irbrc"
ln -sfn "$PWD/ruby/bridge_keys" "$HOME/.bridge_keys"
echo "Linked nterchange, rvmrc, powconfig, gemrc, autotest, irbrc, bridge_keys"

ln -sfn "$PWD/scm/gitconfig" "$HOME/.gitconfig"
ln -sfn "$PWD/scm/gitignore" "$HOME/.gitignore"
ln -sfn "$PWD/scm/hgrc" "$HOME/.hgrc"
echo "Linked gitconfig, gitignore, hgrc"

ln -sfn "$PWD/text/inputrc" "$HOME/.inputrc"
ln -sfn "$PWD/text/nanorc" "$HOME/.nanorc"
echo "Linked inputrc, nanorc"

ln -sfn "$PWD/mail/muttrc" "$HOME/.muttrc"
echo "Linked muttrc"

ln -sfn "$PWD/tmux/tmux.conf" "$HOME/.tmux.conf"
echo "Linked tmux.conf"

# Autojump uses this
mkdir -p "$HOME/.local/share"
echo "Created .local/share directory"

# Properly link ssh config inside .ssh directory
mkdir -p "$HOME/.ssh"
ln -sFn "$HOME/Dropbox/dotfiles/ssh/id_rsa" "$HOME/.ssh/id_rsa"
ln -sFn "$HOME/Dropbox/dotfiles/ssh/id_rsa.pub" "$HOME/.ssh/id_rsa.pub"
ln -sFn "$HOME/Dropbox/dotfiles/ssh/ssh-config" "$HOME/.ssh/ssh-config"
echo "Linked id_rsa, id_rsa.pub, ssh-config"

# Install vim
while true; do
  read -p "Install vim configuration? (y/n) " yn
  case $yn in
    [Yy]* ) echo "Installing vim configuration"
      if [ ! -d "$HOME/.vim" ]; then
        git clone git@github.com:suderman/schala.git "$HOME/.vim"
      fi
      "$HOME/.vim/install.sh"
      break;;
    * ) echo "Done"; exit;;
  esac
done

# Utilities I like to install
# brew install rbenv
# brew install autojump
# brew install ghostscript
# brew install imagemagick
# brew install git
# brew install mysql
# brew install node
# brew install wget
